/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'faq-page': FaqPage;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admins can manage other users and delete content; Editors can edit site content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    taglineLine1: string;
    taglineLine2: string;
    slides?:
      | {
          image: number | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  collection: {
    image: number | Media;
    alt?: string | null;
    heading: string;
    subheading: string;
    description: string;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  categoryGrid: {
    eyebrow: string;
    heading: string;
    categories?:
      | {
          title: string;
          image: number | Media;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  values: {
    eyebrow: string;
    heading: string;
    description: string;
    image: number | Media;
    imageAlt: string;
    items?:
      | {
          index: string;
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  processStrip: {
    eyebrow: string;
    heading: string;
    description: string;
    steps?:
      | {
          step: string;
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  collaborationsSlider: {
    eyebrow: string;
    slides?:
      | {
          image: number | Media;
          imageAlt: string;
          heading: string;
          description: string;
          cardImage: number | Media;
          cardImageAlt: string;
          cardTitle: string;
          cardCaption: string;
          buttonText: string;
          buttonLink: string;
          id?: string | null;
        }[]
      | null;
  };
  pressFeature: {
    eyebrow: string;
    heading: string;
    description: string;
    images?:
      | {
          image: number | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  whyGiada: {
    eyebrow: string;
    heading: string;
    pillars?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
    imageAlt: string;
  };
  testimonials: {
    eyebrow: string;
    heading: string;
    testimonials?:
      | {
          quote: string;
          name: string;
          company: string;
          logo: number | Media;
          /**
           * Invert logo to white — for dark/colored logos that need to read on a light background.
           */
          logoInvert?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  closingCta: {
    heading: string;
    linkText: string;
    href: string;
  };
  imageReel?: {
    images?:
      | {
          image: number | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  hero: {
    eyebrow: string;
    heading: string;
  };
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  closingCta: {
    eyebrow: string;
    heading: string;
    description: string;
    linkText: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        taglineLine1?: T;
        taglineLine2?: T;
        slides?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  collection?:
    | T
    | {
        image?: T;
        alt?: T;
        heading?: T;
        subheading?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  categoryGrid?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        categories?:
          | T
          | {
              title?: T;
              image?: T;
              href?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        items?:
          | T
          | {
              index?: T;
              title?: T;
              text?: T;
              id?: T;
            };
        buttonText?: T;
        buttonLink?: T;
      };
  processStrip?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        steps?:
          | T
          | {
              step?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  collaborationsSlider?:
    | T
    | {
        eyebrow?: T;
        slides?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              heading?: T;
              description?: T;
              cardImage?: T;
              cardImageAlt?: T;
              cardTitle?: T;
              cardCaption?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
            };
      };
  pressFeature?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  whyGiada?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        pillars?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        testimonials?:
          | T
          | {
              quote?: T;
              name?: T;
              company?: T;
              logo?: T;
              logoInvert?: T;
              id?: T;
            };
      };
  closingCta?:
    | T
    | {
        heading?: T;
        linkText?: T;
        href?: T;
      };
  imageReel?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  closingCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        linkText?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}